### ISSUE TITLE
Unicode error when reading RTF

### ISSUE THREAD

**Issue by pombredanne** [brendonh/pyth#42]
When trying to read https://www.gnu.org/licenses/lgpl.rtf I get:

```
>>> b=Rtf15Reader.read(open('lgpl.rtf', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pom/tmp/local/lib/python2.7/site-packages/pyth/plugins/rtf15/reader.py", line 86, in read
    return reader.go()
  File "/home/pom/tmp/local/lib/python2.7/site-packages/pyth/plugins/rtf15/reader.py", line 109, in go
    self.parse()
  File "/home/pom/tmp/local/lib/python2.7/site-packages/pyth/plugins/rtf15/reader.py", line 143, in parse
    self.group.handle(control, digits)
  File "/home/pom/tmp/local/lib/python2.7/site-packages/pyth/plugins/rtf15/reader.py", line 402, in handle
    handler(digits)
  File "/home/pom/tmp/local/lib/python2.7/site-packages/pyth/plugins/rtf15/reader.py", line 521, in handle_ansi_escape
    char = chr(code).decode(self.charset, self.reader.errors)
UnicodeDecodeError: 'cp932' codec can't decode byte 0x81 in position 0: incomplete multibyte sequence
```

**Comment by pombredanne** [comment]
@brendonh Are you still maintaining this repo?

**Comment by hongtaicao** [comment]
I got the same error when parsing the following rtf file.
[00938.rtf.docx](https://github.com/brendonh/pyth/files/1203432/00938.rtf.docx)

I added the .docx extension for uploading purpose only.

log:
Traceback (most recent call last):
  File "C:\test\rtf.py", line 12, in <module>
    doc = Rtf15Reader.read(open(pathname, 'r'))
  File "C:\Program Files\Python27\lib\site-packages\pyth\plugins\rtf15\reader.py", line 86, in read
    return reader.go()
  File "C:\Program Files\Python27\lib\site-packages\pyth\plugins\rtf15\reader.py", line 109, in go
    self.parse()
  File "C:\Program Files\Python27\lib\site-packages\pyth\plugins\rtf15\reader.py", line 143, in parse
    self.group.handle(control, digits)
  File "C:\Program Files\Python27\lib\site-packages\pyth\plugins\rtf15\reader.py", line 402, in handle
    handler(digits)
  File "C:\Program Files\Python27\lib\site-packages\pyth\plugins\rtf15\reader.py", line 521, in handle_ansi_escape
    char = chr(code).decode(self.charset, self.reader.errors)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xc8 in position 0: incomplete multibyte sequence

**Comment by alantygel** [comment]
Same here: 'cp950' codec can't decode byte 0xfa in position 0: incomplete multibyte sequence
